package com.cartalaap.marketplace;
import java.math.BigDecimal;import java.util.List;import org.springframework.http.HttpStatus;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.DeleteMapping;import org.springframework.web.bind.annotation.GetMapping;import org.springframework.web.bind.annotation.PatchMapping;import org.springframework.web.bind.annotation.PathVariable;import org.springframework.web.bind.annotation.PostMapping;import org.springframework.web.bind.annotation.PutMapping;import org.springframework.web.bind.annotation.RequestBody;import org.springframework.web.bind.annotation.RequestMapping;import org.springframework.web.bind.annotation.RequestParam;import org.springframework.web.bind.annotation.ResponseStatus;import org.springframework.web.bind.annotation.RestController;import com.cartalaap.post.PagedResponse;import jakarta.validation.Valid;
@RestController @RequestMapping("/api/marketplace") public class MarketplaceController{private final MarketplaceService service;public MarketplaceController(MarketplaceService service){this.service=service;}
 @GetMapping("/listings")public PagedResponse<ListingResponse>browse(@RequestParam(defaultValue="")String q,@RequestParam(required=false)ListingCategory category,@RequestParam(required=false)BigDecimal minPrice,@RequestParam(required=false)BigDecimal maxPrice,@RequestParam(defaultValue="newest")String sort,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,Authentication auth){return service.browse(q,category,minPrice,maxPrice,sort,page,size,auth);}
 @GetMapping("/listings/{id}")public ListingResponse get(@PathVariable Long id,Authentication auth){return service.get(id,auth);}
 @PostMapping("/listings")@ResponseStatus(HttpStatus.CREATED)public ListingResponse create(@Valid@RequestBody ListingRequest request,Authentication auth){return service.create(request,auth);}
 @PatchMapping("/listings/{id}")public ListingResponse update(@PathVariable Long id,@Valid@RequestBody ListingRequest request,Authentication auth){return service.update(id,request,auth);}
 @PatchMapping("/listings/{id}/status")public ListingResponse status(@PathVariable Long id,@Valid@RequestBody StatusRequest request,Authentication auth){return service.status(id,request,auth);}
 @DeleteMapping("/listings/{id}")@ResponseStatus(HttpStatus.NO_CONTENT)public void delete(@PathVariable Long id,Authentication auth){service.delete(id,auth);}
 @PutMapping("/listings/{id}/favorite")public ListingResponse favorite(@PathVariable Long id,Authentication auth){return service.favorite(id,auth);}
 @DeleteMapping("/listings/{id}/favorite")public ListingResponse unfavorite(@PathVariable Long id,Authentication auth){return service.unfavorite(id,auth);}
 @GetMapping("/saved")public List<ListingResponse> saved(Authentication auth){return service.saved(auth);}
 @GetMapping("/mine")public List<ListingResponse> mine(Authentication auth){return service.mine(auth);}
 @PostMapping("/listings/{id}/reports")@ResponseStatus(HttpStatus.NO_CONTENT)public void report(@PathVariable Long id,@Valid@RequestBody ReportRequest request,Authentication auth){service.report(id,request,auth);}
}
