package com.cartalaap.marketplace;

import java.math.BigDecimal;import java.util.List;import java.util.Locale;
import org.springframework.data.domain.PageRequest;import org.springframework.data.domain.Sort;import org.springframework.data.jpa.domain.Specification;import org.springframework.security.core.Authentication;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import com.cartalaap.common.BadRequestException;import com.cartalaap.common.ForbiddenException;import com.cartalaap.common.NotFoundException;import com.cartalaap.post.PagedResponse;import com.cartalaap.user.CurrentUserService;import com.cartalaap.user.User;
import com.cartalaap.notification.NotificationService;import com.cartalaap.notification.NotificationType;

@Service
public class MarketplaceService{
 private final MarketplaceListingRepository listings;private final MarketplaceFavoriteRepository favorites;private final MarketplaceReportRepository reports;private final CurrentUserService currentUsers;private final NotificationService notificationService;
 public MarketplaceService(MarketplaceListingRepository listings,MarketplaceFavoriteRepository favorites,MarketplaceReportRepository reports,CurrentUserService currentUsers,NotificationService notificationService){this.listings=listings;this.favorites=favorites;this.reports=reports;this.currentUsers=currentUsers;this.notificationService=notificationService;}
 @Transactional(readOnly=true) public PagedResponse<ListingResponse> browse(String q,ListingCategory category,BigDecimal minPrice,BigDecimal maxPrice,String sort,int page,int size,Authentication auth){User current=currentUsers.optional(auth);Specification<MarketplaceListing> spec=(root,query,cb)->cb.conjunction();if(q!=null&&!q.isBlank()){String pattern="%"+q.trim().toLowerCase(Locale.ROOT)+"%";spec=spec.and((root,query,cb)->cb.or(cb.like(cb.lower(root.get("title")),pattern),cb.like(cb.lower(root.get("brand")),pattern),cb.like(cb.lower(root.get("model")),pattern),cb.like(cb.lower(root.get("location")),pattern)));}if(category!=null)spec=spec.and((root,query,cb)->cb.equal(root.get("category"),category));if(minPrice!=null)spec=spec.and((root,query,cb)->cb.greaterThanOrEqualTo(root.get("price"),minPrice));if(maxPrice!=null)spec=spec.and((root,query,cb)->cb.lessThanOrEqualTo(root.get("price"),maxPrice));Sort sorting=switch(sort==null?"newest":sort){case"price_asc"->Sort.by("price").ascending();case"price_desc"->Sort.by("price").descending();default->Sort.by("createdAt").descending();};return PagedResponse.from(listings.findAll(spec,PageRequest.of(Math.max(0,page),Math.max(1,Math.min(40,size)),sorting)).map(l->response(l,current)));}
 @Transactional(readOnly=true) public ListingResponse get(Long id,Authentication auth){return response(find(id),currentUsers.optional(auth));}
 @Transactional public ListingResponse create(ListingRequest request,Authentication auth){User user=currentUsers.require(auth);validate(request);return response(listings.save(new MarketplaceListing(user,request)),user);}
 @Transactional public ListingResponse update(Long id,ListingRequest request,Authentication auth){MarketplaceListing l=find(id);User user=currentUsers.require(auth);owner(l,user);validate(request);l.update(request);return response(l,user);}
 @Transactional public ListingResponse status(Long id,StatusRequest request,Authentication auth){MarketplaceListing l=find(id);User user=currentUsers.require(auth);owner(l,user);l.setStatus(request.status());return response(l,user);}
 @Transactional public void delete(Long id,Authentication auth){MarketplaceListing l=find(id);owner(l,currentUsers.require(auth));listings.delete(l);}
 @Transactional public ListingResponse favorite(Long id,Authentication auth){User user=currentUsers.require(auth);MarketplaceListing l=find(id);if(!favorites.existsByUser_IdAndListing_Id(user.getId(),id)){favorites.save(new MarketplaceFavorite(user,l));notificationService.create(l.getSeller(),user,NotificationType.MARKETPLACE_SAVE,user.getDisplayName()+" saved your listing",id);}return response(l,user);}
 @Transactional public ListingResponse unfavorite(Long id,Authentication auth){User user=currentUsers.require(auth);MarketplaceListing l=find(id);favorites.deleteByUser_IdAndListing_Id(user.getId(),id);favorites.flush();return response(l,user);}
 @Transactional(readOnly=true) public List<ListingResponse> saved(Authentication auth){User user=currentUsers.require(auth);return favorites.findByUser_IdOrderByCreatedAtDesc(user.getId()).stream().map(MarketplaceFavorite::getListing).map(l->response(l,user)).toList();}
 @Transactional(readOnly=true) public List<ListingResponse> mine(Authentication auth){User user=currentUsers.require(auth);return listings.findBySeller_IdOrderByCreatedAtDesc(user.getId()).stream().map(l->response(l,user)).toList();}
 @Transactional public void report(Long id,ReportRequest request,Authentication auth){User user=currentUsers.require(auth);MarketplaceListing l=find(id);if(l.getSeller().getId().equals(user.getId()))throw new BadRequestException("You cannot report your own listing");if(!reports.existsByListing_IdAndReporter_Id(id,user.getId()))reports.save(new MarketplaceReport(l,user,request.reason().trim()));}
 private ListingResponse response(MarketplaceListing l,User current){boolean owned=current!=null&&l.getSeller().getId().equals(current.getId());boolean favorite=current!=null&&favorites.existsByUser_IdAndListing_Id(current.getId(),l.getId());return ListingResponse.from(l,favorite,owned);}
 private MarketplaceListing find(Long id){return listings.findDetailedById(id).orElseThrow(()->new NotFoundException("Listing not found"));}
 private void owner(MarketplaceListing l,User u){if(!l.getSeller().getId().equals(u.getId()))throw new ForbiddenException("You can only change your own listings");}
 private void validate(ListingRequest r){if(r.imageUrls()==null||r.imageUrls().isEmpty())throw new BadRequestException("Add at least one listing image");if(r.maxInvalid())throw new BadRequestException("Invalid listing details");}
}
